name: Publish ${package_name} to PyPI / GitHub

on:
  release:
    types:
      - 'published'
    tags:
      - '*.*.*'

jobs:
  build-n-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.BOT_STEFANZWEIFEL_GIT_AUTO_COMMIT_ACTION }}

      - name: Write CHANGELOG
        run: |
          { printf "### Release ${{ github.event.release.tag_name }} \n\n${{ github.event.release.body }}\n\n"; cat CHANGELOG.md; } > tmp.txt && mv tmp.txt CHANGELOG.md

      - name: Write version in setup.py
        run: |
          sed -i "s/version='.*'/version='${{ github.event.release.tag_name }}'/g" setup.py

      - name: Commit and push new release
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: release ${{ github.event.release.tag_name }}

      - name: Create and push backup branch
        run: |
          backup_branch="release/${{ github.event.release.tag_name }}"
          git checkout -b "$backup_branch"
          git push origin "$backup_branch"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Build source and wheel distributions
        run: |
          python -m pip install --upgrade build twine
          python -m build
          twine check --strict dist/*
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
